### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by decadenza** [gc-ant/digiholo2D#1]
Which C++ files are the ones to reproduce the algorithm proposed in the paper _Tile-Based Two-Dimensional Phase
Unwrapping for Digital Holography Using a Modular Framework_?

The structure of the folder is not clear to me.

**Comment by Maahk** [comment]
The cpp files of the algorithms you can find in src/algorithms, the corresponding headers in include/algorithms. 

To compile the program and run it yourself you need all the files in both the src/ & include/ directories.

**Comment by geo-ant** [comment]
I am one of the original authors and I have spent a little time updating the project to use CMake and Conan. It should now build on Linux and Win platforms, but I only briefly tested it on Linux. I have updated the readme and added a few words of wisdom (i guess). 

I don't intend to maintain this code anymore, but I wanted to leave it in a state that is halfway usable.
